version: '3.8'
services:
  base:
    build: .
    tty: true
    environment:
      - PORT=3000
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - .:/app
      - /app/node_modules

  api:
    extends: base
    command: yarn start
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    links:
      - mongo

  test-unit:
    extends: base
    command: yarn test:unit

  test-integration:
    extends: base
    command: yarn test:integration
    links:
      - mongo
    environment:
      - PORT=3001

  mongo:
    image: mongo:4.4.2
    logging:
      driver: none
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
