version: '3.8'
services:
  api:
    build: .
    links:
      - mongo
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  mongo:
    image: mongo:4.4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
