version: '3.8'
services:
  base:
    build: .
    tty: true
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

  test-unit:
    extends: base
    command: yarn test:unit

  mongo:
    image: mongo:4.4.2
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
