name: build-and-test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run build

  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn run test:unit

  integration-tests:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:4.4.2
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ''
          MONGO_INITDB_ROOT_PASSWORD: ''

    env:
      JWT_SECRET: integration
      MONGO_HOST: localhost
      MONGO_PORT: 27017

    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn run test:integration
